## JimuReport 配置
#jimureport:
#  # 是否启用报表
#  enabled: true
#  # 报表访问路径
#  path: /jmreport
#  # 数据库配置（如果需要独立数据源）
#  datasource:
#    enabled: true
#    url: jdbc:mysql://localhost:3306/jimu?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: "051213"
#    driver-class-name: com.mysql.cj.jdbc.Driver